// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea3_GestionEmpleados.Data;

#nullable disable

namespace Tarea3_GestionEmpleados.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarea3_GestionEmpleados.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasData(
                        new { Id = 1,  Activo = true,  Apellidos = "Ramírez Solano",   Departamento = "TI",               FechaIngreso = new DateTime(2020, 3, 15), Nombre = "Carlos",  Salario = 1200000m },
                        new { Id = 2,  Activo = true,  Apellidos = "González Mora",    Departamento = "TI",               FechaIngreso = new DateTime(2021, 6, 1),  Nombre = "Ana",     Salario = 1100000m },
                        new { Id = 3,  Activo = true,  Apellidos = "Vargas Pérez",     Departamento = "TI",               FechaIngreso = new DateTime(2022, 1, 10), Nombre = "Laura",   Salario = 980000m  },
                        new { Id = 4,  Activo = true,  Apellidos = "Méndez Castillo",  Departamento = "Finanzas",         FechaIngreso = new DateTime(2019, 8, 20), Nombre = "Jorge",   Salario = 1500000m },
                        new { Id = 5,  Activo = true,  Apellidos = "Fernández López",  Departamento = "Finanzas",         FechaIngreso = new DateTime(2020, 11, 5), Nombre = "María",   Salario = 1350000m },
                        new { Id = 6,  Activo = true,  Apellidos = "Jiménez Arias",    Departamento = "Recursos Humanos", FechaIngreso = new DateTime(2023, 2, 14), Nombre = "Andrés",  Salario = 900000m  },
                        new { Id = 7,  Activo = false, Apellidos = "Castro Brenes",    Departamento = "Recursos Humanos", FechaIngreso = new DateTime(2023, 7, 3),  Nombre = "Sofía",   Salario = 850000m  },
                        new { Id = 8,  Activo = true,  Apellidos = "Alvarado Rojas",   Departamento = "Operaciones",      FechaIngreso = new DateTime(2021, 4, 22), Nombre = "Diego",   Salario = 760000m  },
                        new { Id = 9,  Activo = true,  Apellidos = "Herrera Núñez",    Departamento = "Operaciones",      FechaIngreso = new DateTime(2022, 9, 18), Nombre = "Valeria", Salario = 720000m  },
                        new { Id = 10, Activo = true,  Apellidos = "Quesada Elizondo", Departamento = "Gerencia",         FechaIngreso = new DateTime(2018, 1, 7),  Nombre = "Roberto", Salario = 3500000m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
